import type { NextPage } from "next";
import Link from "next/link";
import Head from "next/head";

import * as PageStyles from "../../styles/pages/shared";

const Tools: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <PageStyles.Container>
          <PageStyles.Title>Tools</PageStyles.Title>
          <p>Tools coming soon</p>
          <ul>
            <li>
              <Link href="/tools/percentage-calculator">
                Percentage Calculator
              </Link>
            </li>
            <li>In development - Wod Timer</li>
          </ul>
        </PageStyles.Container>
      </main>
    </>
  );
};

export default Tools;
