import type { NextPage } from "next";
import Head from "next/head";
import PercentageCalculator from "../../components/PercentageCalculator";

import * as PageStyles from "../../styles/pages/shared";

const Tools: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <PageStyles.Container>
          <PageStyles.Title>Percentage of calculator</PageStyles.Title>
          <p>
            Enter your one rep max in KG into the calculator below to get an
            insight into what the percentage breakdown of your one rep max is.
          </p>
          <PercentageCalculator />
        </PageStyles.Container>
      </main>
    </>
  );
};

export default Tools;
