import type { NextPage } from "next";
import Head from "next/head";
import FeaturedBlogCard from "../../components/Blog/FeaturedBlogCard";
import welcomeImg from "../../assets/images/blog/welcome-to-whiteboard-fitness/cleanandjerk.jpeg";

import * as PageStyles from "../../styles/pages/shared";

const Blog: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <PageStyles.Container>
          <PageStyles.Title>Blog</PageStyles.Title>

          <FeaturedBlogCard
            title="Welcome to The Fitness Corner"
            description="The first post from The Fitness Corner and what you can expect in the future"
            link="blog/welcome-to-the-fitness-corner"
            author="Kieran Venison"
            imageData={welcomeImg}
          />
        </PageStyles.Container>
      </main>
    </>
  );
};

export default Blog;
