import type { NextPage } from "next";
import Head from "next/head";

import * as PageStyles from "../../styles/pages/shared";

const Blog: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <PageStyles.Container>
          <PageStyles.Title>Whiteboard Fitness</PageStyles.Title>
        </PageStyles.Container>
      </main>
    </>
  );
};

export default Blog;
