import type { NextPage } from "next";
import Head from "next/head";
import * as PageStyles from "../styles/pages/shared";
import welcomeImg from "../assets/images/blog/welcome-to-whiteboard-fitness/cleanandjerk.jpeg";
import MiniBlogCard from "../components/Blog/MiniBlogCard";
import FeaturedBlogCard from "../components/Blog/FeaturedBlogCard";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <PageStyles.Container>
          <FeaturedBlogCard
            title="Welcome to Whiteboard Fitness"
            description="The first post from Whiteboard Fitness and what you can expect in the future"
            link="/blog/welcome-to-whiteboard-fitness"
            author="Kieran Venison"
            imageData={welcomeImg}
          />

          <h2>Blogs</h2>

          <PageStyles.ArticlesGrid>
            <MiniBlogCard
              title="Welcome to The Whiteboard Fitness"
              link="/blog/welcome-to-whiteboard-fitness"
              imageData={welcomeImg}
            />
          </PageStyles.ArticlesGrid>
        </PageStyles.Container>
      </main>
    </>
  );
};

export default Home;
